// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: carport_display

#ifndef _CARPORT_DISPLAY_UI_H
#define _CARPORT_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void blink_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_Label8(lv_event_t * e);
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1859540261);    // assets/Texas_A&M_Aggies_Primary_Logo_(2021-Present) (2).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
