// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: carport_display

#include "ui.h"

void on_encoder_press(lv_event_t * e)
{
	// Your code here
}
